### ISSUE TITLE
Add backing store for line state

### ISSUE THREAD

**Issue by Andrew-William-Smith** [SamLab17/HelpHours#12]
## Description
Currently, we have the issue that if the app were to go down during office hours, we would lose the state of the line.  This problem is a result of our current architecture, which keeps all state in memory in the Python interpreter without any form of persistence.  There are two options that we could consider in order to persist the state of the line across application restarts:

1. **Restore line from database on startup.**  This is the easiest option as it only requires a single SQL query; however, it could be a bit slow and requires us to store a bit more information in the database, such as names and any other line state we need to save across restarts.
2. **Introduce a Redis store for the line.** This would completely replace our current Python queue, offloading the work of queue and data management to Redis.  [Redis](https://redis.io/) is an in-memory key-value and list store that can persist data to/restore data from disk automatically.  It introduces a bit more complexity into our architecture, but it would allow persistence without storing too much information in the database, in addition to making parallelisation easier if we were to introduce concurrency other than that provided by Flask.

## Open Questions
Which approach would y'all prefer?  Both have pros and cons, but they can all be worked around; I don't particularly like storing application state in a database and thus am more partial to using Redis, but if we don't want to add a dependency then that's understandable.

**Comment by SamLab17** [comment]
I like the Redis approach; I don't want to store any more data in the database than we need to.

**Comment by ClosingBracket** [comment]
Nina fixed it!
